set(FOXY_TESTING ON)
set(Boost_USE_STATIC_LIBS ON)
set(BOOST_ROOT "/Users/cmaza/cpp/boost-168/install")
add_compile_options("/permissive-" "/bigobj")
include("/Users/cmaza/cpp/vcpkg/scripts/buildsystems/vcpkg.cmake")